import type { Portfolio } from "./types";

export const MOCK_PORTFOLIO: Portfolio = {
  profile: {
    id: "mock-profile",
    full_name: "Santosh Metri",
    headline: "Software engineer building products people actually use",
    bio: "This is sample content. Connect Supabase and use Admin to replace it with your real bio, skills, and projects.",
    location: "Remote",
    headshot_url: null,
    resume_url: null,
    updated_at: null,
  },
  skills: [
    { id: "s1", name: "TypeScript", category: "Languages", level: 5, sort_order: 0, published: true },
    { id: "s2", name: "React / Next.js", category: "Frontend", level: 5, sort_order: 1, published: true },
    { id: "s3", name: "React Native", category: "Mobile", level: 4, sort_order: 2, published: true },
    { id: "s4", name: "Postgres", category: "Data", level: 4, sort_order: 3, published: true },
    { id: "s5", name: "Supabase", category: "Backend", level: 4, sort_order: 4, published: true },
  ],
  experiences: [
    {
      id: "e1",
      company: "Example Studio",
      role: "Senior Software Engineer",
      location: "Remote",
      start_date: "2022-01-01",
      end_date: null,
      highlights: "Led web and mobile delivery for customer-facing products.\nSet up design systems, CI, and observability.",
      sort_order: 0,
      published: true,
    },
    {
      id: "e2",
      company: "Previous Company",
      role: "Software Engineer",
      location: "London",
      start_date: "2019-03-01",
      end_date: "2021-12-01",
      highlights: "Shipped features across the stack.\nMentored junior engineers.",
      sort_order: 1,
      published: true,
    },
  ],
  projects: [
    {
      id: "p1",
      title: "Portfolio OS",
      summary: "This site — a public portfolio with a private admin CMS.",
      description: "Next.js on the web, Expo on native, one Supabase backend.",
      stack: "Next.js, Expo, Supabase, Tailwind",
      live_url: null,
      repo_url: null,
      image_url: null,
      featured: true,
      sort_order: 0,
      published: true,
    },
  ],
  education: [
    {
      id: "ed1",
      institution: "University",
      credential: "BSc Computer Science",
      start_date: "2015-09-01",
      end_date: "2019-06-01",
      details: null,
      sort_order: 0,
      published: true,
    },
  ],
  socialLinks: [
    { id: "l1", label: "GitHub", url: "https://github.com", sort_order: 0, published: true },
    { id: "l2", label: "LinkedIn", url: "https://linkedin.com", sort_order: 1, published: true },
  ],
  settings: {
    id: "mock-settings",
    site_title: "Santosh Metri",
    tagline: "Engineer. Builder. Editor of this page.",
    seo_description: "Online portfolio and selected work.",
    contact_email: "hello@example.com",
    availability: "Open to interesting work",
    updated_at: null,
  },
};
